# Generated by Django 2.2.10 on 2020-04-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firmregistrationstatusmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('Received_Registration', models.TextField()),
                ('Registered_Firms', models.TextField()),
                ('Hold_Registration', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('reg_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmname', models.CharField(max_length=100)),
                ('firmhead', models.CharField(max_length=100)),
                ('addr', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('request_date', models.TextField()),
                ('extension', models.CharField(max_length=30)),
            ],
        ),
    ]
